#!/bin/bash
NOW=$(date '+%F:%H:%M:%S')
ssh_home=$(ls -al ~/.ssh)
# setup your parameters
ssh_host="git@github.com"
remoteUrl="https://github.com/"
user="Claodio"
# ------------------------------

repname="chap-app-templating"
if [ -z "$repname" ]
then
	echo "I can initialize a git repos when Repos Name is [NULL]"
	exit 1
fi

echo "$repname"

git_remoteAddress=`echo $ssh_host:$user/$repname.git`
git_remoteUrl=`echo $remoteUrl$user/$repname.git`
git remote add $repname "ssh://$git_remoteAddress"
git remote add $repname "ssh://$git_remoteUrl"
#Verify new remote
git remote -v

GitHubAddress=$(echo "[32m[ $git_remoteAddress[m")
$(git remote get-url "$git_remoteAddress")
$(git remote get-url "$git_remoteUrl")

printf "%s\n%s\n%s\n" "verify-address:$git_remoteAddress" "verify-url:$git_remoteUrl" "listing-ssh:$ssh_home"

git add . && git status && git commit -a -m"all in $repname is about to be committed to $GitHubAddress $NOW"
git push $repname master

chmod +x ./remote_git